apiVersion: v1

kind: Service

metadata:
  name: hello-app-service
  labels:
    app: hello-app

spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 38080
